// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audit.dart';
import 'api/sync.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuditEntryRefDto dco_decode_audit_entry_ref_dto(dynamic raw);

  @protected
  AuditReportDto dco_decode_audit_report_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EntryDto dco_decode_box_autoadd_entry_dto(dynamic raw);

  @protected
  GenOptionsDto dco_decode_box_autoadd_gen_options_dto(dynamic raw);

  @protected
  SyncConfigDto dco_decode_box_autoadd_sync_config_dto(dynamic raw);

  @protected
  BreachHitDto dco_decode_breach_hit_dto(dynamic raw);

  @protected
  BreachReportDto dco_decode_breach_report_dto(dynamic raw);

  @protected
  EntryDto dco_decode_entry_dto(dynamic raw);

  @protected
  GenOptionsDto dco_decode_gen_options_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuditEntryRefDto> dco_decode_list_audit_entry_ref_dto(dynamic raw);

  @protected
  List<BreachHitDto> dco_decode_list_breach_hit_dto(dynamic raw);

  @protected
  List<EntryDto> dco_decode_list_entry_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReuseGroupDto> dco_decode_list_reuse_group_dto(dynamic raw);

  @protected
  SyncConfigDto? dco_decode_opt_box_autoadd_sync_config_dto(dynamic raw);

  @protected
  ReuseGroupDto dco_decode_reuse_group_dto(dynamic raw);

  @protected
  StrengthDto dco_decode_strength_dto(dynamic raw);

  @protected
  SyncConfigDto dco_decode_sync_config_dto(dynamic raw);

  @protected
  SyncResultDto dco_decode_sync_result_dto(dynamic raw);

  @protected
  TotpDto dco_decode_totp_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuditEntryRefDto sse_decode_audit_entry_ref_dto(SseDeserializer deserializer);

  @protected
  AuditReportDto sse_decode_audit_report_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EntryDto sse_decode_box_autoadd_entry_dto(SseDeserializer deserializer);

  @protected
  GenOptionsDto sse_decode_box_autoadd_gen_options_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncConfigDto sse_decode_box_autoadd_sync_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  BreachHitDto sse_decode_breach_hit_dto(SseDeserializer deserializer);

  @protected
  BreachReportDto sse_decode_breach_report_dto(SseDeserializer deserializer);

  @protected
  EntryDto sse_decode_entry_dto(SseDeserializer deserializer);

  @protected
  GenOptionsDto sse_decode_gen_options_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuditEntryRefDto> sse_decode_list_audit_entry_ref_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<BreachHitDto> sse_decode_list_breach_hit_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EntryDto> sse_decode_list_entry_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReuseGroupDto> sse_decode_list_reuse_group_dto(
    SseDeserializer deserializer,
  );

  @protected
  SyncConfigDto? sse_decode_opt_box_autoadd_sync_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ReuseGroupDto sse_decode_reuse_group_dto(SseDeserializer deserializer);

  @protected
  StrengthDto sse_decode_strength_dto(SseDeserializer deserializer);

  @protected
  SyncConfigDto sse_decode_sync_config_dto(SseDeserializer deserializer);

  @protected
  SyncResultDto sse_decode_sync_result_dto(SseDeserializer deserializer);

  @protected
  TotpDto sse_decode_totp_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audit_entry_ref_dto(
    AuditEntryRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audit_report_dto(
    AuditReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entry_dto(
    EntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gen_options_dto(
    GenOptionsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_config_dto(
    SyncConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_breach_hit_dto(BreachHitDto self, SseSerializer serializer);

  @protected
  void sse_encode_breach_report_dto(
    BreachReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_dto(EntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_gen_options_dto(GenOptionsDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_entry_ref_dto(
    List<AuditEntryRefDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_breach_hit_dto(
    List<BreachHitDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_dto(List<EntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reuse_group_dto(
    List<ReuseGroupDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_config_dto(
    SyncConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reuse_group_dto(ReuseGroupDto self, SseSerializer serializer);

  @protected
  void sse_encode_strength_dto(StrengthDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_config_dto(SyncConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_sync_result_dto(SyncResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_totp_dto(TotpDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
