// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audit.dart';
import 'api/sync.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiVaultInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -873487488;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<EntryDto> crateApiVaultAddEntry({required EntryDto entry});

  Future<AuditReportDto> crateApiAuditAuditVault();

  Future<void> crateApiVaultChangeMasterPassword({required String newPassword});

  Future<BreachReportDto> crateApiAuditCheckBreaches();

  Future<void> crateApiVaultCreateVault({
    required String path,
    required String password,
  });

  Future<void> crateApiVaultDeleteEntry({required String id});

  Future<String> crateApiVaultExportCsv();

  Future<String> crateApiVaultGeneratePassphrase({
    required PassphraseOptionsDto opts,
  });

  Future<String> crateApiVaultGeneratePassword({required GenOptionsDto opts});

  Future<EntryDto> crateApiVaultGetEntry({required String id});

  Future<SyncConfigDto?> crateApiSyncGetSyncConfig();

  Future<int> crateApiVaultImportCsv({required String text});

  Future<void> crateApiVaultInitApp();

  Future<bool> crateApiVaultIsUnlocked();

  Future<void> crateApiSyncJoinRemoteVault({
    required String path,
    required String url,
    required String username,
    required String password,
  });

  Future<List<EntryDto>> crateApiVaultListArchived();

  Future<List<EntryDto>> crateApiVaultListEntries();

  Future<void> crateApiVaultLockVault();

  Future<StrengthDto> crateApiVaultPasswordStrength({required String password});

  Future<void> crateApiSyncRegisterAccount({
    required String url,
    required String username,
  });

  Future<void> crateApiVaultSetArchived({
    required String id,
    required bool archived,
  });

  Future<SyncResultDto> crateApiSyncSyncNow();

  Future<TotpDto> crateApiVaultTotpNow({required String input});

  Future<void> crateApiVaultUnlockVault({
    required String path,
    required String password,
  });

  Future<EntryDto> crateApiVaultUpdateEntry({required EntryDto entry});

  Future<bool> crateApiVaultVaultExists({required String path});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<EntryDto> crateApiVaultAddEntry({required EntryDto entry}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_entry_dto(entry, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultAddEntryConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultAddEntryConstMeta =>
      const TaskConstMeta(debugName: "add_entry", argNames: ["entry"]);

  @override
  Future<AuditReportDto> crateApiAuditAuditVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_audit_report_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuditAuditVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuditAuditVaultConstMeta =>
      const TaskConstMeta(debugName: "audit_vault", argNames: []);

  @override
  Future<void> crateApiVaultChangeMasterPassword({
    required String newPassword,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(newPassword, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultChangeMasterPasswordConstMeta,
        argValues: [newPassword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultChangeMasterPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "change_master_password",
        argNames: ["newPassword"],
      );

  @override
  Future<BreachReportDto> crateApiAuditCheckBreaches() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_breach_report_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuditCheckBreachesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuditCheckBreachesConstMeta =>
      const TaskConstMeta(debugName: "check_breaches", argNames: []);

  @override
  Future<void> crateApiVaultCreateVault({
    required String path,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultCreateVaultConstMeta,
        argValues: [path, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["path", "password"],
  );

  @override
  Future<void> crateApiVaultDeleteEntry({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultDeleteEntryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultDeleteEntryConstMeta =>
      const TaskConstMeta(debugName: "delete_entry", argNames: ["id"]);

  @override
  Future<String> crateApiVaultExportCsv() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultExportCsvConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultExportCsvConstMeta =>
      const TaskConstMeta(debugName: "export_csv", argNames: []);

  @override
  Future<String> crateApiVaultGeneratePassphrase({
    required PassphraseOptionsDto opts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_passphrase_options_dto(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultGeneratePassphraseConstMeta,
        argValues: [opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultGeneratePassphraseConstMeta =>
      const TaskConstMeta(debugName: "generate_passphrase", argNames: ["opts"]);

  @override
  Future<String> crateApiVaultGeneratePassword({required GenOptionsDto opts}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_gen_options_dto(opts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultGeneratePasswordConstMeta,
        argValues: [opts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultGeneratePasswordConstMeta =>
      const TaskConstMeta(debugName: "generate_password", argNames: ["opts"]);

  @override
  Future<EntryDto> crateApiVaultGetEntry({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultGetEntryConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultGetEntryConstMeta =>
      const TaskConstMeta(debugName: "get_entry", argNames: ["id"]);

  @override
  Future<SyncConfigDto?> crateApiSyncGetSyncConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_sync_config_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncGetSyncConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncGetSyncConfigConstMeta =>
      const TaskConstMeta(debugName: "get_sync_config", argNames: []);

  @override
  Future<int> crateApiVaultImportCsv({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultImportCsvConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultImportCsvConstMeta =>
      const TaskConstMeta(debugName: "import_csv", argNames: ["text"]);

  @override
  Future<void> crateApiVaultInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiVaultIsUnlocked() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultIsUnlockedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultIsUnlockedConstMeta =>
      const TaskConstMeta(debugName: "is_unlocked", argNames: []);

  @override
  Future<void> crateApiSyncJoinRemoteVault({
    required String path,
    required String url,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncJoinRemoteVaultConstMeta,
        argValues: [path, url, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncJoinRemoteVaultConstMeta =>
      const TaskConstMeta(
        debugName: "join_remote_vault",
        argNames: ["path", "url", "username", "password"],
      );

  @override
  Future<List<EntryDto>> crateApiVaultListArchived() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultListArchivedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultListArchivedConstMeta =>
      const TaskConstMeta(debugName: "list_archived", argNames: []);

  @override
  Future<List<EntryDto>> crateApiVaultListEntries() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_entry_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultListEntriesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultListEntriesConstMeta =>
      const TaskConstMeta(debugName: "list_entries", argNames: []);

  @override
  Future<void> crateApiVaultLockVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<StrengthDto> crateApiVaultPasswordStrength({
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strength_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultPasswordStrengthConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPasswordStrengthConstMeta =>
      const TaskConstMeta(
        debugName: "password_strength",
        argNames: ["password"],
      );

  @override
  Future<void> crateApiSyncRegisterAccount({
    required String url,
    required String username,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncRegisterAccountConstMeta,
        argValues: [url, username],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncRegisterAccountConstMeta =>
      const TaskConstMeta(
        debugName: "register_account",
        argNames: ["url", "username"],
      );

  @override
  Future<void> crateApiVaultSetArchived({
    required String id,
    required bool archived,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_bool(archived, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultSetArchivedConstMeta,
        argValues: [id, archived],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSetArchivedConstMeta => const TaskConstMeta(
    debugName: "set_archived",
    argNames: ["id", "archived"],
  );

  @override
  Future<SyncResultDto> crateApiSyncSyncNow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_result_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSyncSyncNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncSyncNowConstMeta =>
      const TaskConstMeta(debugName: "sync_now", argNames: []);

  @override
  Future<TotpDto> crateApiVaultTotpNow({required String input}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_totp_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultTotpNowConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultTotpNowConstMeta =>
      const TaskConstMeta(debugName: "totp_now", argNames: ["input"]);

  @override
  Future<void> crateApiVaultUnlockVault({
    required String path,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultUnlockVaultConstMeta,
        argValues: [path, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultUnlockVaultConstMeta => const TaskConstMeta(
    debugName: "unlock_vault",
    argNames: ["path", "password"],
  );

  @override
  Future<EntryDto> crateApiVaultUpdateEntry({required EntryDto entry}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_entry_dto(entry, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultUpdateEntryConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultUpdateEntryConstMeta =>
      const TaskConstMeta(debugName: "update_entry", argNames: ["entry"]);

  @override
  Future<bool> crateApiVaultVaultExists({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultExistsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultExistsConstMeta =>
      const TaskConstMeta(debugName: "vault_exists", argNames: ["path"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuditEntryRefDto dco_decode_audit_entry_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AuditEntryRefDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      detail: dco_decode_String(arr[2]),
    );
  }

  @protected
  AuditReportDto dco_decode_audit_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AuditReportDto(
      score: dco_decode_u_8(arr[0]),
      total: dco_decode_usize(arr[1]),
      withPassword: dco_decode_usize(arr[2]),
      weak: dco_decode_list_audit_entry_ref_dto(arr[3]),
      reused: dco_decode_list_reuse_group_dto(arr[4]),
      stale: dco_decode_list_audit_entry_ref_dto(arr[5]),
      empty: dco_decode_list_audit_entry_ref_dto(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EntryDto dco_decode_box_autoadd_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_entry_dto(raw);
  }

  @protected
  GenOptionsDto dco_decode_box_autoadd_gen_options_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gen_options_dto(raw);
  }

  @protected
  PassphraseOptionsDto dco_decode_box_autoadd_passphrase_options_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_passphrase_options_dto(raw);
  }

  @protected
  SyncConfigDto dco_decode_box_autoadd_sync_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sync_config_dto(raw);
  }

  @protected
  BreachHitDto dco_decode_breach_hit_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BreachHitDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      count: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  BreachReportDto dco_decode_breach_report_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BreachReportDto(
      checked: dco_decode_usize(arr[0]),
      hits: dco_decode_list_breach_hit_dto(arr[1]),
    );
  }

  @protected
  CustomFieldDto dco_decode_custom_field_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CustomFieldDto(
      label: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
      hidden: dco_decode_bool(arr[2]),
    );
  }

  @protected
  EntryDto dco_decode_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return EntryDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      username: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      notes: dco_decode_String(arr[5]),
      totp: dco_decode_String(arr[6]),
      tags: dco_decode_list_String(arr[7]),
      favorite: dco_decode_bool(arr[8]),
      createdAt: dco_decode_i_64(arr[9]),
      updatedAt: dco_decode_i_64(arr[10]),
      itemType: dco_decode_String(arr[11]),
      customFields: dco_decode_list_custom_field_dto(arr[12]),
      passwordHistory: dco_decode_list_password_history_dto(arr[13]),
      archived: dco_decode_bool(arr[14]),
    );
  }

  @protected
  GenOptionsDto dco_decode_gen_options_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GenOptionsDto(
      length: dco_decode_u_32(arr[0]),
      lower: dco_decode_bool(arr[1]),
      upper: dco_decode_bool(arr[2]),
      digits: dco_decode_bool(arr[3]),
      symbols: dco_decode_bool(arr[4]),
      excludeAmbiguous: dco_decode_bool(arr[5]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AuditEntryRefDto> dco_decode_list_audit_entry_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audit_entry_ref_dto).toList();
  }

  @protected
  List<BreachHitDto> dco_decode_list_breach_hit_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_breach_hit_dto).toList();
  }

  @protected
  List<CustomFieldDto> dco_decode_list_custom_field_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_custom_field_dto).toList();
  }

  @protected
  List<EntryDto> dco_decode_list_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_dto).toList();
  }

  @protected
  List<PasswordHistoryDto> dco_decode_list_password_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_password_history_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReuseGroupDto> dco_decode_list_reuse_group_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reuse_group_dto).toList();
  }

  @protected
  SyncConfigDto? dco_decode_opt_box_autoadd_sync_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_sync_config_dto(raw);
  }

  @protected
  PassphraseOptionsDto dco_decode_passphrase_options_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PassphraseOptionsDto(
      wordCount: dco_decode_u_32(arr[0]),
      separator: dco_decode_String(arr[1]),
      capitalize: dco_decode_bool(arr[2]),
      addNumber: dco_decode_bool(arr[3]),
    );
  }

  @protected
  PasswordHistoryDto dco_decode_password_history_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PasswordHistoryDto(
      password: dco_decode_String(arr[0]),
      changedAt: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  ReuseGroupDto dco_decode_reuse_group_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ReuseGroupDto(entries: dco_decode_list_audit_entry_ref_dto(arr[0]));
  }

  @protected
  StrengthDto dco_decode_strength_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StrengthDto(
      score: dco_decode_u_8(arr[0]),
      crackTime: dco_decode_String(arr[1]),
      warning: dco_decode_String(arr[2]),
      suggestions: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  SyncConfigDto dco_decode_sync_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SyncConfigDto(
      url: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      sinceRevision: dco_decode_i_64(arr[2]),
      lastSyncAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  SyncResultDto dco_decode_sync_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SyncResultDto(
      pushed: dco_decode_u_32(arr[0]),
      pulled: dco_decode_u_32(arr[1]),
      serverRevision: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  TotpDto dco_decode_totp_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TotpDto(
      code: dco_decode_String(arr[0]),
      secondsRemaining: dco_decode_u_64(arr[1]),
      period: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuditEntryRefDto sse_decode_audit_entry_ref_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return AuditEntryRefDto(id: var_id, title: var_title, detail: var_detail);
  }

  @protected
  AuditReportDto sse_decode_audit_report_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_u_8(deserializer);
    var var_total = sse_decode_usize(deserializer);
    var var_withPassword = sse_decode_usize(deserializer);
    var var_weak = sse_decode_list_audit_entry_ref_dto(deserializer);
    var var_reused = sse_decode_list_reuse_group_dto(deserializer);
    var var_stale = sse_decode_list_audit_entry_ref_dto(deserializer);
    var var_empty = sse_decode_list_audit_entry_ref_dto(deserializer);
    return AuditReportDto(
      score: var_score,
      total: var_total,
      withPassword: var_withPassword,
      weak: var_weak,
      reused: var_reused,
      stale: var_stale,
      empty: var_empty,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EntryDto sse_decode_box_autoadd_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_entry_dto(deserializer));
  }

  @protected
  GenOptionsDto sse_decode_box_autoadd_gen_options_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gen_options_dto(deserializer));
  }

  @protected
  PassphraseOptionsDto sse_decode_box_autoadd_passphrase_options_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_passphrase_options_dto(deserializer));
  }

  @protected
  SyncConfigDto sse_decode_box_autoadd_sync_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sync_config_dto(deserializer));
  }

  @protected
  BreachHitDto sse_decode_breach_hit_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_count = sse_decode_u_64(deserializer);
    return BreachHitDto(id: var_id, title: var_title, count: var_count);
  }

  @protected
  BreachReportDto sse_decode_breach_report_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_checked = sse_decode_usize(deserializer);
    var var_hits = sse_decode_list_breach_hit_dto(deserializer);
    return BreachReportDto(checked: var_checked, hits: var_hits);
  }

  @protected
  CustomFieldDto sse_decode_custom_field_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    var var_hidden = sse_decode_bool(deserializer);
    return CustomFieldDto(
      label: var_label,
      value: var_value,
      hidden: var_hidden,
    );
  }

  @protected
  EntryDto sse_decode_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_totp = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_favorite = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_itemType = sse_decode_String(deserializer);
    var var_customFields = sse_decode_list_custom_field_dto(deserializer);
    var var_passwordHistory = sse_decode_list_password_history_dto(
      deserializer,
    );
    var var_archived = sse_decode_bool(deserializer);
    return EntryDto(
      id: var_id,
      title: var_title,
      username: var_username,
      password: var_password,
      url: var_url,
      notes: var_notes,
      totp: var_totp,
      tags: var_tags,
      favorite: var_favorite,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      itemType: var_itemType,
      customFields: var_customFields,
      passwordHistory: var_passwordHistory,
      archived: var_archived,
    );
  }

  @protected
  GenOptionsDto sse_decode_gen_options_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_length = sse_decode_u_32(deserializer);
    var var_lower = sse_decode_bool(deserializer);
    var var_upper = sse_decode_bool(deserializer);
    var var_digits = sse_decode_bool(deserializer);
    var var_symbols = sse_decode_bool(deserializer);
    var var_excludeAmbiguous = sse_decode_bool(deserializer);
    return GenOptionsDto(
      length: var_length,
      lower: var_lower,
      upper: var_upper,
      digits: var_digits,
      symbols: var_symbols,
      excludeAmbiguous: var_excludeAmbiguous,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AuditEntryRefDto> sse_decode_list_audit_entry_ref_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AuditEntryRefDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audit_entry_ref_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<BreachHitDto> sse_decode_list_breach_hit_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BreachHitDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_breach_hit_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<CustomFieldDto> sse_decode_list_custom_field_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomFieldDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_custom_field_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntryDto> sse_decode_list_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PasswordHistoryDto> sse_decode_list_password_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PasswordHistoryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_password_history_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReuseGroupDto> sse_decode_list_reuse_group_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReuseGroupDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reuse_group_dto(deserializer));
    }
    return ans_;
  }

  @protected
  SyncConfigDto? sse_decode_opt_box_autoadd_sync_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_sync_config_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PassphraseOptionsDto sse_decode_passphrase_options_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wordCount = sse_decode_u_32(deserializer);
    var var_separator = sse_decode_String(deserializer);
    var var_capitalize = sse_decode_bool(deserializer);
    var var_addNumber = sse_decode_bool(deserializer);
    return PassphraseOptionsDto(
      wordCount: var_wordCount,
      separator: var_separator,
      capitalize: var_capitalize,
      addNumber: var_addNumber,
    );
  }

  @protected
  PasswordHistoryDto sse_decode_password_history_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_password = sse_decode_String(deserializer);
    var var_changedAt = sse_decode_i_64(deserializer);
    return PasswordHistoryDto(password: var_password, changedAt: var_changedAt);
  }

  @protected
  ReuseGroupDto sse_decode_reuse_group_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_audit_entry_ref_dto(deserializer);
    return ReuseGroupDto(entries: var_entries);
  }

  @protected
  StrengthDto sse_decode_strength_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_u_8(deserializer);
    var var_crackTime = sse_decode_String(deserializer);
    var var_warning = sse_decode_String(deserializer);
    var var_suggestions = sse_decode_list_String(deserializer);
    return StrengthDto(
      score: var_score,
      crackTime: var_crackTime,
      warning: var_warning,
      suggestions: var_suggestions,
    );
  }

  @protected
  SyncConfigDto sse_decode_sync_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_sinceRevision = sse_decode_i_64(deserializer);
    var var_lastSyncAt = sse_decode_i_64(deserializer);
    return SyncConfigDto(
      url: var_url,
      username: var_username,
      sinceRevision: var_sinceRevision,
      lastSyncAt: var_lastSyncAt,
    );
  }

  @protected
  SyncResultDto sse_decode_sync_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pushed = sse_decode_u_32(deserializer);
    var var_pulled = sse_decode_u_32(deserializer);
    var var_serverRevision = sse_decode_i_64(deserializer);
    return SyncResultDto(
      pushed: var_pushed,
      pulled: var_pulled,
      serverRevision: var_serverRevision,
    );
  }

  @protected
  TotpDto sse_decode_totp_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_secondsRemaining = sse_decode_u_64(deserializer);
    var var_period = sse_decode_u_64(deserializer);
    return TotpDto(
      code: var_code,
      secondsRemaining: var_secondsRemaining,
      period: var_period,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audit_entry_ref_dto(
    AuditEntryRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_audit_report_dto(
    AuditReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.score, serializer);
    sse_encode_usize(self.total, serializer);
    sse_encode_usize(self.withPassword, serializer);
    sse_encode_list_audit_entry_ref_dto(self.weak, serializer);
    sse_encode_list_reuse_group_dto(self.reused, serializer);
    sse_encode_list_audit_entry_ref_dto(self.stale, serializer);
    sse_encode_list_audit_entry_ref_dto(self.empty, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_entry_dto(
    EntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_entry_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gen_options_dto(
    GenOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gen_options_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_passphrase_options_dto(
    PassphraseOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_passphrase_options_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sync_config_dto(
    SyncConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sync_config_dto(self, serializer);
  }

  @protected
  void sse_encode_breach_hit_dto(BreachHitDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_u_64(self.count, serializer);
  }

  @protected
  void sse_encode_breach_report_dto(
    BreachReportDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.checked, serializer);
    sse_encode_list_breach_hit_dto(self.hits, serializer);
  }

  @protected
  void sse_encode_custom_field_dto(
    CustomFieldDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.value, serializer);
    sse_encode_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_entry_dto(EntryDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_String(self.totp, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_bool(self.favorite, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_String(self.itemType, serializer);
    sse_encode_list_custom_field_dto(self.customFields, serializer);
    sse_encode_list_password_history_dto(self.passwordHistory, serializer);
    sse_encode_bool(self.archived, serializer);
  }

  @protected
  void sse_encode_gen_options_dto(
    GenOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.length, serializer);
    sse_encode_bool(self.lower, serializer);
    sse_encode_bool(self.upper, serializer);
    sse_encode_bool(self.digits, serializer);
    sse_encode_bool(self.symbols, serializer);
    sse_encode_bool(self.excludeAmbiguous, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audit_entry_ref_dto(
    List<AuditEntryRefDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audit_entry_ref_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_breach_hit_dto(
    List<BreachHitDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_breach_hit_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_custom_field_dto(
    List<CustomFieldDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_custom_field_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_dto(
    List<EntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_password_history_dto(
    List<PasswordHistoryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_password_history_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reuse_group_dto(
    List<ReuseGroupDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reuse_group_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_sync_config_dto(
    SyncConfigDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_sync_config_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_passphrase_options_dto(
    PassphraseOptionsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.wordCount, serializer);
    sse_encode_String(self.separator, serializer);
    sse_encode_bool(self.capitalize, serializer);
    sse_encode_bool(self.addNumber, serializer);
  }

  @protected
  void sse_encode_password_history_dto(
    PasswordHistoryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.password, serializer);
    sse_encode_i_64(self.changedAt, serializer);
  }

  @protected
  void sse_encode_reuse_group_dto(
    ReuseGroupDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_audit_entry_ref_dto(self.entries, serializer);
  }

  @protected
  void sse_encode_strength_dto(StrengthDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.score, serializer);
    sse_encode_String(self.crackTime, serializer);
    sse_encode_String(self.warning, serializer);
    sse_encode_list_String(self.suggestions, serializer);
  }

  @protected
  void sse_encode_sync_config_dto(
    SyncConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_i_64(self.sinceRevision, serializer);
    sse_encode_i_64(self.lastSyncAt, serializer);
  }

  @protected
  void sse_encode_sync_result_dto(
    SyncResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.pushed, serializer);
    sse_encode_u_32(self.pulled, serializer);
    sse_encode_i_64(self.serverRevision, serializer);
  }

  @protected
  void sse_encode_totp_dto(TotpDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_u_64(self.secondsRemaining, serializer);
    sse_encode_u_64(self.period, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
