// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent`, `breach_count`, `map_ref`, `with_vault`

/// 로컬 보안 점검 (네트워크 없음).
Future<AuditReportDto> auditVault() =>
    RustLib.instance.api.crateApiAuditAuditVault();

/// 볼트의 모든 비밀번호를 유출 검사. 같은 비밀번호는 한 번만 조회한다.
Future<BreachReportDto> checkBreaches() =>
    RustLib.instance.api.crateApiAuditCheckBreaches();

class AuditEntryRefDto {
  final String id;
  final String title;
  final String detail;

  const AuditEntryRefDto({
    required this.id,
    required this.title,
    required this.detail,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEntryRefDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          detail == other.detail;
}

class AuditReportDto {
  final int score;
  final BigInt total;
  final BigInt withPassword;
  final List<AuditEntryRefDto> weak;
  final List<ReuseGroupDto> reused;
  final List<AuditEntryRefDto> stale;
  final List<AuditEntryRefDto> empty;

  const AuditReportDto({
    required this.score,
    required this.total,
    required this.withPassword,
    required this.weak,
    required this.reused,
    required this.stale,
    required this.empty,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      total.hashCode ^
      withPassword.hashCode ^
      weak.hashCode ^
      reused.hashCode ^
      stale.hashCode ^
      empty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditReportDto &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          total == other.total &&
          withPassword == other.withPassword &&
          weak == other.weak &&
          reused == other.reused &&
          stale == other.stale &&
          empty == other.empty;
}

class BreachHitDto {
  final String id;
  final String title;

  /// 이 비밀번호가 유출 데이터에서 발견된 횟수
  final BigInt count;

  const BreachHitDto({
    required this.id,
    required this.title,
    required this.count,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreachHitDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          count == other.count;
}

class BreachReportDto {
  final BigInt checked;
  final List<BreachHitDto> hits;

  const BreachReportDto({required this.checked, required this.hits});

  @override
  int get hashCode => checked.hashCode ^ hits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BreachReportDto &&
          runtimeType == other.runtimeType &&
          checked == other.checked &&
          hits == other.hits;
}

class ReuseGroupDto {
  final List<AuditEntryRefDto> entries;

  const ReuseGroupDto({required this.entries});

  @override
  int get hashCode => entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReuseGroupDto &&
          runtimeType == other.runtimeType &&
          entries == other.entries;
}
