// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `agent`, `http_err`, `normalize_url`, `now_secs`, `valid_username`, `with_vault`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Prelogin`, `SyncResp`

/// 현재 볼트의 동기화 설정 (없으면 None).
Future<SyncConfigDto?> getSyncConfig() =>
    RustLib.instance.api.crateApiSyncGetSyncConfig();

/// 서버에 새 계정 등록 후 이 볼트를 연결.
Future<void> registerAccount({required String url, required String username}) =>
    RustLib.instance.api.crateApiSyncRegisterAccount(
      url: url,
      username: username,
    );

/// push + pull 한 사이클.
Future<SyncResultDto> syncNow() => RustLib.instance.api.crateApiSyncSyncNow();

/// 새 기기 합류: 서버 계정의 헤더로 로컬 볼트를 만들고 첫 동기화까지 수행.
Future<void> joinRemoteVault({
  required String path,
  required String url,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSyncJoinRemoteVault(
  path: path,
  url: url,
  username: username,
  password: password,
);

class SyncConfigDto {
  final String url;
  final String username;
  final PlatformInt64 sinceRevision;
  final PlatformInt64 lastSyncAt;

  const SyncConfigDto({
    required this.url,
    required this.username,
    required this.sinceRevision,
    required this.lastSyncAt,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      username.hashCode ^
      sinceRevision.hashCode ^
      lastSyncAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConfigDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          username == other.username &&
          sinceRevision == other.sinceRevision &&
          lastSyncAt == other.lastSyncAt;
}

class SyncResultDto {
  final int pushed;
  final int pulled;
  final PlatformInt64 serverRevision;

  const SyncResultDto({
    required this.pushed,
    required this.pulled,
    required this.serverRevision,
  });

  @override
  int get hashCode =>
      pushed.hashCode ^ pulled.hashCode ^ serverRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncResultDto &&
          runtimeType == other.runtimeType &&
          pushed == other.pushed &&
          pulled == other.pulled &&
          serverRevision == other.serverRevision;
}
