// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_err`, `from_dto`, `to_dto`, `with_vault`

Future<bool> vaultExists({required String path}) =>
    RustLib.instance.api.crateApiVaultVaultExists(path: path);

Future<void> createVault({required String path, required String password}) =>
    RustLib.instance.api.crateApiVaultCreateVault(
      path: path,
      password: password,
    );

Future<void> unlockVault({required String path, required String password}) =>
    RustLib.instance.api.crateApiVaultUnlockVault(
      path: path,
      password: password,
    );

/// 잠금 — Vault 드롭으로 vault_key가 메모리에서 zeroize된다.
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

Future<bool> isUnlocked() => RustLib.instance.api.crateApiVaultIsUnlocked();

Future<void> changeMasterPassword({required String newPassword}) => RustLib
    .instance
    .api
    .crateApiVaultChangeMasterPassword(newPassword: newPassword);

Future<List<EntryDto>> listEntries() =>
    RustLib.instance.api.crateApiVaultListEntries();

Future<EntryDto> getEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultGetEntry(id: id);

Future<EntryDto> addEntry({required EntryDto entry}) =>
    RustLib.instance.api.crateApiVaultAddEntry(entry: entry);

Future<EntryDto> updateEntry({required EntryDto entry}) =>
    RustLib.instance.api.crateApiVaultUpdateEntry(entry: entry);

Future<void> deleteEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultDeleteEntry(id: id);

Future<List<EntryDto>> listArchived() =>
    RustLib.instance.api.crateApiVaultListArchived();

Future<void> setArchived({required String id, required bool archived}) =>
    RustLib.instance.api.crateApiVaultSetArchived(id: id, archived: archived);

/// 범용 CSV 텍스트를 가져와 항목으로 추가. 추가된 개수 반환.
Future<int> importCsv({required String text}) =>
    RustLib.instance.api.crateApiVaultImportCsv(text: text);

/// 활성 항목을 CSV 평문으로 내보냄 (암호화되지 않음).
Future<String> exportCsv() => RustLib.instance.api.crateApiVaultExportCsv();

Future<String> generatePassword({required GenOptionsDto opts}) =>
    RustLib.instance.api.crateApiVaultGeneratePassword(opts: opts);

Future<String> generatePassphrase({required PassphraseOptionsDto opts}) =>
    RustLib.instance.api.crateApiVaultGeneratePassphrase(opts: opts);

Future<StrengthDto> passwordStrength({required String password}) =>
    RustLib.instance.api.crateApiVaultPasswordStrength(password: password);

Future<TotpDto> totpNow({required String input}) =>
    RustLib.instance.api.crateApiVaultTotpNow(input: input);

class CustomFieldDto {
  final String label;
  final String value;
  final bool hidden;

  const CustomFieldDto({
    required this.label,
    required this.value,
    required this.hidden,
  });

  @override
  int get hashCode => label.hashCode ^ value.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldDto &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          hidden == other.hidden;
}

class EntryDto {
  final String id;
  final String title;
  final String username;
  final String password;
  final String url;
  final String notes;
  final String totp;
  final List<String> tags;
  final bool favorite;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  /// "login" | "note" | "card"
  final String itemType;
  final List<CustomFieldDto> customFields;
  final List<PasswordHistoryDto> passwordHistory;
  final bool archived;

  const EntryDto({
    required this.id,
    required this.title,
    required this.username,
    required this.password,
    required this.url,
    required this.notes,
    required this.totp,
    required this.tags,
    required this.favorite,
    required this.createdAt,
    required this.updatedAt,
    required this.itemType,
    required this.customFields,
    required this.passwordHistory,
    required this.archived,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      totp.hashCode ^
      tags.hashCode ^
      favorite.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      itemType.hashCode ^
      customFields.hashCode ^
      passwordHistory.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          totp == other.totp &&
          tags == other.tags &&
          favorite == other.favorite &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          itemType == other.itemType &&
          customFields == other.customFields &&
          passwordHistory == other.passwordHistory &&
          archived == other.archived;
}

class GenOptionsDto {
  final int length;
  final bool lower;
  final bool upper;
  final bool digits;
  final bool symbols;
  final bool excludeAmbiguous;

  const GenOptionsDto({
    required this.length,
    required this.lower,
    required this.upper,
    required this.digits,
    required this.symbols,
    required this.excludeAmbiguous,
  });

  @override
  int get hashCode =>
      length.hashCode ^
      lower.hashCode ^
      upper.hashCode ^
      digits.hashCode ^
      symbols.hashCode ^
      excludeAmbiguous.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenOptionsDto &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          lower == other.lower &&
          upper == other.upper &&
          digits == other.digits &&
          symbols == other.symbols &&
          excludeAmbiguous == other.excludeAmbiguous;
}

class PassphraseOptionsDto {
  final int wordCount;
  final String separator;
  final bool capitalize;
  final bool addNumber;

  const PassphraseOptionsDto({
    required this.wordCount,
    required this.separator,
    required this.capitalize,
    required this.addNumber,
  });

  @override
  int get hashCode =>
      wordCount.hashCode ^
      separator.hashCode ^
      capitalize.hashCode ^
      addNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PassphraseOptionsDto &&
          runtimeType == other.runtimeType &&
          wordCount == other.wordCount &&
          separator == other.separator &&
          capitalize == other.capitalize &&
          addNumber == other.addNumber;
}

class PasswordHistoryDto {
  final String password;
  final PlatformInt64 changedAt;

  const PasswordHistoryDto({required this.password, required this.changedAt});

  @override
  int get hashCode => password.hashCode ^ changedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasswordHistoryDto &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          changedAt == other.changedAt;
}

class StrengthDto {
  final int score;
  final String crackTime;
  final String warning;
  final List<String> suggestions;

  const StrengthDto({
    required this.score,
    required this.crackTime,
    required this.warning,
    required this.suggestions,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      crackTime.hashCode ^
      warning.hashCode ^
      suggestions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrengthDto &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          crackTime == other.crackTime &&
          warning == other.warning &&
          suggestions == other.suggestions;
}

class TotpDto {
  final String code;
  final BigInt secondsRemaining;
  final BigInt period;

  const TotpDto({
    required this.code,
    required this.secondsRemaining,
    required this.period,
  });

  @override
  int get hashCode =>
      code.hashCode ^ secondsRemaining.hashCode ^ period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TotpDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          secondsRemaining == other.secondsRemaining &&
          period == other.period;
}
