// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_err`, `from_dto`, `to_dto`, `with_vault`

Future<bool> vaultExists({required String path}) =>
    RustLib.instance.api.crateApiVaultVaultExists(path: path);

Future<void> createVault({required String path, required String password}) =>
    RustLib.instance.api.crateApiVaultCreateVault(
      path: path,
      password: password,
    );

Future<void> unlockVault({required String path, required String password}) =>
    RustLib.instance.api.crateApiVaultUnlockVault(
      path: path,
      password: password,
    );

/// 잠금 — Vault 드롭으로 vault_key가 메모리에서 zeroize된다.
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

Future<bool> isUnlocked() => RustLib.instance.api.crateApiVaultIsUnlocked();

Future<void> changeMasterPassword({required String newPassword}) => RustLib
    .instance
    .api
    .crateApiVaultChangeMasterPassword(newPassword: newPassword);

Future<List<EntryDto>> listEntries() =>
    RustLib.instance.api.crateApiVaultListEntries();

Future<EntryDto> getEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultGetEntry(id: id);

Future<EntryDto> addEntry({required EntryDto entry}) =>
    RustLib.instance.api.crateApiVaultAddEntry(entry: entry);

Future<EntryDto> updateEntry({required EntryDto entry}) =>
    RustLib.instance.api.crateApiVaultUpdateEntry(entry: entry);

Future<void> deleteEntry({required String id}) =>
    RustLib.instance.api.crateApiVaultDeleteEntry(id: id);

Future<String> generatePassword({required GenOptionsDto opts}) =>
    RustLib.instance.api.crateApiVaultGeneratePassword(opts: opts);

Future<StrengthDto> passwordStrength({required String password}) =>
    RustLib.instance.api.crateApiVaultPasswordStrength(password: password);

Future<TotpDto> totpNow({required String input}) =>
    RustLib.instance.api.crateApiVaultTotpNow(input: input);

class EntryDto {
  final String id;
  final String title;
  final String username;
  final String password;
  final String url;
  final String notes;
  final String totp;
  final List<String> tags;
  final bool favorite;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const EntryDto({
    required this.id,
    required this.title,
    required this.username,
    required this.password,
    required this.url,
    required this.notes,
    required this.totp,
    required this.tags,
    required this.favorite,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      totp.hashCode ^
      tags.hashCode ^
      favorite.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          totp == other.totp &&
          tags == other.tags &&
          favorite == other.favorite &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class GenOptionsDto {
  final int length;
  final bool lower;
  final bool upper;
  final bool digits;
  final bool symbols;
  final bool excludeAmbiguous;

  const GenOptionsDto({
    required this.length,
    required this.lower,
    required this.upper,
    required this.digits,
    required this.symbols,
    required this.excludeAmbiguous,
  });

  @override
  int get hashCode =>
      length.hashCode ^
      lower.hashCode ^
      upper.hashCode ^
      digits.hashCode ^
      symbols.hashCode ^
      excludeAmbiguous.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenOptionsDto &&
          runtimeType == other.runtimeType &&
          length == other.length &&
          lower == other.lower &&
          upper == other.upper &&
          digits == other.digits &&
          symbols == other.symbols &&
          excludeAmbiguous == other.excludeAmbiguous;
}

class StrengthDto {
  final int score;
  final String crackTime;
  final String warning;
  final List<String> suggestions;

  const StrengthDto({
    required this.score,
    required this.crackTime,
    required this.warning,
    required this.suggestions,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      crackTime.hashCode ^
      warning.hashCode ^
      suggestions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrengthDto &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          crackTime == other.crackTime &&
          warning == other.warning &&
          suggestions == other.suggestions;
}

class TotpDto {
  final String code;
  final BigInt secondsRemaining;
  final BigInt period;

  const TotpDto({
    required this.code,
    required this.secondsRemaining,
    required this.period,
  });

  @override
  int get hashCode =>
      code.hashCode ^ secondsRemaining.hashCode ^ period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TotpDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          secondsRemaining == other.secondsRemaining &&
          period == other.period;
}
